cluster: "sbatch --cpus-per-task={threads} --mem={resources.mem_mb} --time={resources.time}"
jobs: 50
use-conda: true
use-singularity: true
printshellcmds: true
latency-wait: 60
rerun-incomplete: true
default-resources:
  - mem_mb=4000
  - time="02:00:00"
